### ISSUE TITLE
Нет пистолета у снайпериста

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#10]
И гилле нету. какой же енто снайперист xdxdxd

**Comment by OneScheer** [comment]
Исправил

**Comment by 10Dozen** [comment]
В кит kit_bund_mm добавь еще пару магазинов для MP7. Снайперка не влазит в рюкзак, так что если что - ее придется бросить и расчитывать ток на то что с собой. Выложить патрики всегда успеется

**Comment by OneScheer** [comment]
Добавил магазинов
https://github.com/rempopo/CO21_One_Way_Ticket.lythium/blob/5f7b9a6cb7d799d5910429ad3c792287c335fc84/dzn_gear/Kits.sqf#L124

**Comment by 10Dozen** [comment]
Окда
