### ISSUE TITLE
Мож фенек добавить?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#12]
Все таки разведка или как штабная.

Вроде както можно кастомную текстуру лепить на технику прямо в миссии

**Comment by OneScheer** [comment]
не знаю как лепить, поэтому не использую. Вроде где-то есть моды на ретекстуры фенека.

**Comment by 10Dozen** [comment]
Бля, братан, если закрывать все потому что ты не знаешь, то так можно и половую жизнь тебе закрыть не открывая.

**Comment by OneScheer** [comment]
Ну слушай, я даже если бы знал как ретекстурить фенек, его бы не добавил в свою миску. Потому что хочу чтобы все ездили на Динго!

**Comment by 10Dozen** [comment]
Ну если хочешь то какочешь, а могли б ретекстур в сборку добавить по поводу. А раз никому не нужно то и не добавим никогда

**Comment by OneScheer** [comment]
не добавил, нахуй надо
