### ISSUE TITLE
Мож прятать минометы после уничтожения?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#13]
А то они КАК ЖИВОЙ... А СУКА НЕ ЖИВОЙ ЕБАТЬ

**Comment by OneScheer** [comment]
Сделал

**Comment by 10Dozen** [comment]
Косметические правки

https://github.com/rempopo/CO21_One_Way_Ticket.lythium/commit/79a9bddf9c21f08442b67eb3e91a4fa75eb4d5b9
https://github.com/rempopo/CO21_One_Way_Ticket.lythium/commit/50f2c9862b12e537d457d962eefb81d37275b9ec
