### ISSUE TITLE
Както тяп-ляп зоны накиданы

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#14]
Чото хз, с одной стороны пускай, с другой - а чо они ебта шароебятся по горам бесцельно (чтобы их задетектить можно и было в теплак и смаслить реее).

Может сделать триггер типа Детектед в 300-500 м от мортиры -- спаунятся на горах и начинают набегать к минометам (ну или маршрут им выдавать на рандомного СЛа (или ПЛа ахаха):
`private _randomLeaderPos = getPos ( selectRandom ((call BIS_fnc_listPlayer) select { leader _x }) );`

Но в общем как хочыш

Ну и как минимум патрули по вершинам холмов натыкать. а то будут рандомно ползать у основания и ничого не видеть

**Comment by OneScheer** [comment]
Сдвину зоны ближе к вершинам, но удалять их не буду.

**Comment by 10Dozen** [comment]
Так сделай так чтобы боты не торчали праздно наружу, в чем смысл то ходить туда сюда если у нас теплаки?

**Comment by OneScheer** [comment]
Почему тогда талибы бегают по горам в Афганистане, если у всех есть теплаки?

**Comment by 10Dozen** [comment]
Так уж и рандомно бегают.

Ну кароч я предложил сделать типа засаду, но на свое усмотрение обрабатываю тикет

**Comment by OneScheer** [comment]
ну просто может возникнуть ситуация, когда лим пошлёт 1'2 на гору смотреть-наблюдать, а 1'1 внизу будет шароёбиться у миномётов и в итоге боты заспавняться под горой всем пипец

**Comment by 10Dozen** [comment]
Вылезли из пещер11111 
Ну или спаунт за пределами АО, а саму АО по-уже, мы ж не хотим посылать гансов в глубину талибских позиций

**Comment by 10Dozen** [comment]
Ок
