### ISSUE TITLE
Интро текст на НИМИЦЕКОМ, ШИЗИКБЛЯ

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#18]
Ты РЮЗЗКЕ
Пиши по РЮЗЗКЕ

Название можешь на немецком, местоположение и слова "ОПЕРАЦИЯ" -- на русском

**Comment by OneScheer** [comment]
пшёл отсюда, унтерменш. И давай-ка пиши тикеты нормально, еблан.

**Comment by 10Dozen** [comment]
Что твой маленький мозг не может понять? Ты не знаешь куда ты высрал интро текст? Мне тебя жаль

**Comment by OneScheer** [comment]
Я уже всё понял и исправил, так что перестань срунькать.

**Comment by 10Dozen** [comment]
Молодец
