### ISSUE TITLE
Почему 1`6 в середине ростера?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#2]
<img src='http://puu.sh/AvZ8A/b2483d52fd.jpg' />

**Comment by OneScheer** [comment]
Так получилось, есть пути решения?

**Comment by 10Dozen** [comment]
Удалить всех игровых и добавить в правильном порядке

**Comment by 10Dozen** [comment]
И названия отрядов нормальные, а не KSK какието

**Comment by OneScheer** [comment]
Исправил

**Comment by 10Dozen** [comment]
Ок
