### ISSUE TITLE
А где обещанный в брифинге фонетический алфавит на немецком?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#20]

**Comment by OneScheer** [comment]
Если бы ты повнимательнее почитал брифинг, то понял.  
https://github.com/rempopo/CO21_One_Way_Ticket.lythium/blob/778602816c123be64d1c03d7db185df00345437b/dzn_tSFramework/Modules/tSNotes/Notes.sqf#L72

**Comment by 10Dozen** [comment]
Так и сюда хуйни ( в своей миссии), вместо латинского автозаполнения:
https://github.com/10Dozen/dzn_tSFramework/blob/d46aa386934c80f9a61c137e17a4662bcffd6149/dzn_tSFramework/Modules/MissionDefaults/Settings.sqf#L29
 А то наверное никто и не узнает что оно там есть и зачемто нужно

**Comment by 10Dozen** [comment]
Ок
