### ISSUE TITLE
5 км поездок в гору -- это нормально?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#5]
Не верится както

**Comment by OneScheer** [comment]
Только что ездил, пять минут от базы, на миске выйдет где-то десять

**Comment by 10Dozen** [comment]
Хуй знает, чото дохуя как по мне. Тем более лиманий поедет в объезд по восточной дороге - а там все 20 минут охуительных путешествий

**Comment by OneScheer** [comment]
Лиманий это знает, так что его проблемы. Я же не обязан делать для него короткий маршрут для суперфланга)

**Comment by 10Dozen** [comment]
Пускай будет так
