### ISSUE TITLE
Зачем G36C ком.отделения?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#6]
Это ж CQBшная хуитка, тем более смысл прицела на нем? Православная g36a с 3.5х 2д кратником практически то же самое что этот ваш спектре на короткостволе. 

(мааам ниудобно в калиматор целится -- ну ну сыначка, тевтонцы терпели и нам велели)

**Comment by OneScheer** [comment]
Исправил

**Comment by 10Dozen** [comment]
Ок
