### ISSUE TITLE
Брефенг кревой

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO21_One_Way_Ticket.lythium#9]
Изучи фиксы из https://github.com/rempopo/CO21_One_Way_Ticket.lythium/pull/8 и делай по подобию

**Comment by 10Dozen** [comment]
Ещё домержи из моего бранче, давай укажем что наша арта сама не осилит гарантировано накрыть талибов

**Comment by OneScheer** [comment]
Исправил

**Comment by 10Dozen** [comment]
Поправил еще маленько в мастере. 
Ок
